#!/bin/bash
set -e

# GIZMODIR
# GIZMOGIT
# GIZMOROLESDIR
# GIZMOROLESGIT
# AUTOMATIONDIR
# AUTOMATIONGIT
# GIZMO_PROFILE

env_file=/tmp/$RANDOM.txt
gizmo_setup="$HOME/.gizmo_setup"

echo "*** Please note some operation requires root access. You might be asked for your root password"
echo ""
env > $env_file

config() {
  if grep -q "^$1=" $env_file; then
    echo "  $1=${!1}" >&2
    echo "${!1}"
  else
    echo "  $1=$2" >&2
    echo "$2"
  fi
}

gitget() {
  #Dir 1, git 2, name 3
  if [ ! -d $1/.git ]; then
    echo "$3 clonning '$2' in '$1' "
    git clone $2 $1
  else
    echo "$3 pull '$2' in '$1' "
    cd $1
    git pull
  fi
}

echo "Config variables:"
GIZMODIR=$(config "GIZMODIR" "$HOME/gizmo")
GIZMOGIT=$(config "GIZMOGIT" "git@github.com:AutomationWithAnsible/gizmo.git")
GIZMOROLESDIR=$(config "GIZMOROLESDIR" "$HOME/gizmo/roles")
GIZMOROLESGIT=$(config "GIZMOROLESGIT" "git@github.com:AutomationWithAnsible/gizmoroles.git")
#AUTOMATIONDIR=$(config "AUTOMATIONDIR" "$HOME/automation")
#AUTOMATIONGIT=$(config "AUTOMATIONGIT" "git@github.com:enginyoyen/ansible-best-practises.git")
GIZMO_PROFILE=$(config "GIZMO_PROFILE" "$HOME/.gizmo_profile")
source_line="source $GIZMO_PROFILE"
echo

if [ ! $(which git) ]; then
  echo "please install git and try again..."
  exit 1
fi

if [ ! $(which pip) ]; then
  if [ ! $(which easy_install) ]; then
    echo "Your python environment is not set properly. Please check your environment ..."
    exit 1
  else
    echo "installing pip"
    sudo easy_install pip
  fi
fi


gitget $GIZMODIR $GIZMOGIT "gizmo"
chmod 700 $GIZMODIR

echo "Installing Ansible and its requirements using PIP"
cd $GIZMODIR
pip install -r $GIZMODIR/requirements.txt

gitget $GIZMOROLESDIR $GIZMOROLESGIT "gizmo roles"

##
#gitget $AUTOMATIONDIR $AUTOMATIONGIT "Automation"

# Shell profile
cat profile > $HOME/.gizmo_profile
if [ "$SHELL" = "/bin/zsh" ]; then
  SHELLPROFILE="$HOME/.zshrc"
elif [ "$SHELL" = "/bin/bash" ]; then
  SHELLPROFILE="$HOME/.bash_profile"
else
  echo "** Unknown shell '$SHELL'"
fi

if [ $(grep -c "$source_line" $SHELLPROFILE ) -eq 0 ]; then
  echo "Adding gizmo_profile to $SHELLPROFILE..."
  echo "$source_line" >> $SHELLPROFILE
fi